file_length:
  warning: 256
  error: 512
line_length: 80
type_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 32
    error: 64
  allowed_symbols: ["_"]
type_body_length:
  warning: 128
  error: 256
identifier_name:
  min_length:
    error: 1
    warning: 1
  max_length:
    warning: 16
    error: 32
